/// <reference types="tree-sitter-cli/dsl" />
// @ts-check
//
module.exports = {
  keywords: {
    // Basic query keywords
    SELECT: /select/i,
    FROM: /from/i,
    WHERE: /where/i,
    GROUP_BY: /group\s+by/i,
    HAVING: /having/i,
    ORDER_BY: /order\s+by/i,
    ORDER: /order/i,
    BY: /by/i,
    LIMIT: /limit/i,
    OFFSET: /offset/i,
    
    // Join keywords
    JOIN: /join/i,
    INNER_JOIN: /inner\s+join/i,
    LEFT_JOIN: /left(\s+outer)?\s+join/i,
    RIGHT_JOIN: /right(\s+outer)?\s+join/i,
    FULL_JOIN: /full(\s+outer)?\s+join/i,
    CROSS_JOIN: /cross\s+join/i,
    ON: /on/i,
    
    // Table manipulation
    CREATE: /create/i,
    ALTER: /alter/i,
    DROP: /drop/i,
    TRUNCATE: /truncate/i,
    TABLE: /table/i,
    
    // Data manipulation
    INSERT: /insert/i,
    UPDATE: /update/i,
    DELETE: /delete/i,
    INTO: /into/i,
    VALUES: /values/i,
    SET: /set/i,
    
    // Common clauses
    AS: /as/i,
    AND: /and/i,
    OR: /or/i,
    NOT: /not/i,
    NULL: /null/i,
    IS: /is/i,
    IN: /in/i,
    BETWEEN: /between/i,
    LIKE: /like/i,
    ILIKE: /ilike/i,
    
    // Data types
    INTEGER: /integer|int/i,
    BIGINT: /bigint/i,
    SMALLINT: /smallint/i,
    NUMERIC: /numeric/i,
    DECIMAL: /decimal/i,
    REAL: /real/i,
    DOUBLE_PRECISION: /double\s+precision/i,
    VARCHAR: /varchar/i,
    CHAR: /char/i,
    TEXT: /text/i,
    BOOLEAN: /boolean|bool/i,
    DATE: /date/i,
    TIME: /time/i,
    TIMESTAMP: /timestamp/i,
    INTERVAL: /interval/i,
    JSON: /json/i,
    JSONB: /jsonb/i,
    UUID: /uuid/i,
    
    // Constraints
    PRIMARY_KEY: /primary\s+key/i,
    FOREIGN_KEY: /foreign\s+key/i,
    UNIQUE: /unique/i,
    CHECK: /check/i,
    DEFAULT: /default/i,
    REFERENCES: /references/i,
    NOT_NULL: /not\s+null/i,
    
    // Transactions
    BEGIN: /begin/i,
    COMMIT: /commit/i,
    ROLLBACK: /rollback/i,
    TRANSACTION: /transaction/i,
    
    // Common PostgreSQL functions
    COUNT: /count/i,
    SUM: /sum/i,
    AVG: /avg/i,
    MIN: /min/i,
    MAX: /max/i,
    COALESCE: /coalesce/i,
    NULLIF: /nullif/i,
    CAST: /cast/i,
    
    // PostgreSQL specific
    WITH: /with/i,
    RECURSIVE: /recursive/i,
    RETURNING: /returning/i,
    USING: /using/i,
    DISTINCT: /distinct/i,
    ALL: /all/i,
    ANY: /any/i,
    SOME: /some/i,
    CASE: /case/i,
    WHEN: /when/i,
    THEN: /then/i,
    ELSE: /else/i,
    END: /end/i,
    
    // Additional PostgreSQL keywords
    OVER: /over/i,
    PARTITION_BY: /partition\s+by/i,
    WINDOW: /window/i,
    LATERAL: /lateral/i,
    MATERIALIZED: /materialized/i,
    VIEW: /view/i,
    INDEX: /index/i,
    CONCURRENTLY: /concurrently/i,
    EXTENSION: /extension/i,
    SCHEMA: /schema/i,
    SEQUENCE: /sequence/i,
    TRIGGER: /trigger/i,
    FUNCTION: /function/i,
    PROCEDURE: /procedure/i,
    LANGUAGE: /language/i,
    RETURNS: /returns/i,
    RETURN: /return/i,
    DECLARE: /declare/i,
    EXCEPTION: /exception/i,
    RAISE: /raise/i,
    NOTICE: /notice/i,
    INFO: /info/i,
    WARNING: /warning/i,
    ERROR: /error/i,
  },
};
