/// <reference types="tree-sitter-cli/dsl" />
// @ts-check


const keywords = [
    "ALL",
    "ALTER",
    "AND",
    "ANY",
    "AS",
    "ASC",
    "AVG",
    "BEGIN",
    "BETWEEN",
    "BIGINT",
    "BOOLEAN",
    "CASE",
    "CAST",
    "CHAR",
    "CHECK",
    "COALESCE",
    "COMMIT",
    "CONCURRENTLY",
    "COUNT",
    "CREATE",
    "CROSS_JOIN",
    "DATE",
    "DECIMAL",
    "DECLARE",
    "DEFAULT",
    "DELETE",
    "DESC",
    "DISTINCT",
    "DOUBLE_PRECISION",
    "DROP",
    "ELSE",
    "END",
    "ERROR",
    "EXCEPTION",
    "EXTENSION",
    "FOREIGN_KEY",
    "FROM",
    "FULL_JOIN",
    "FUNCTION",
    "GROUP_BY",
    "HAVING",
    "ILIKE",
    "IN",
    "INDEX",
    "INFO",
    "INNER_JOIN",
    "INSERT",
    "INTEGER",
    "INTERVAL",
    "INTO",
    "IS",
    "JOIN",
    "JSON",
    "JSONB",
    "LANGUAGE",
    "LATERAL",
    "LEFT_JOIN",
    "LIKE",
    "LIMIT",
    "MATERIALIZED",
    "MAX",
    "MIN",
    "NOT",
    "NOTICE",
    "NOT_NULL",
    "NULL",
    "NULLIF",
    "NULLS_FIRST",
    "NULLS_LAST",
    "NUMERIC",
    "OFFSET",
    "ON",
    "OR",
    "ORDER_BY",
    "OVER",
    "PARTITION_BY",
    "PRIMARY_KEY",
    "PROCEDURE",
    "RAISE",
    "REAL",
    "RECURSIVE",
    "REFERENCES",
    "RETURN",
    "RETURNING",
    "RETURNS",
    "RIGHT_JOIN",
    "ROLLBACK",
    "SCHEMA",
    "SELECT",
    "SEQUENCE",
    "SET",
    "SMALLINT",
    "SOME",
    "SUM",
    "TABLE",
    "TEXT",
    "THEN",
    "TIME",
    "TIMESTAMP",
    "TRANSACTION",
    "TRIGGER",
    "TRUNCATE",
    "UNIQUE",
    "UPDATE",
    "USING",
    "UUID",
    "VALUES",
    "VARCHAR",
    "VIEW",
    "WARNING",
    "WHEN",
    "WHERE",
    "WINDOW",
    "WITH",
]

const keywordRules = {}

for (const keyword of keywords) {
  keywordRules[keyword] = toKeyword(keyword)
}

module.exports = {
  keywords: {
    ...keywordRules,
    WILDCARD: () => "*",
  },
};

/**
  * Converts a string to a keyword
  * @param {string} word
  * @returns {() => Rule}
  */
function toKeyword(word) {
  const cleanedWord = word.toLowerCase().replace(/_/g, " ");
  return () => choice(cleanedWord.toLowerCase(), cleanedWord.toUpperCase());
}
