name: Publish to npm
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      package-name: "@janhoon/tree-sitter-sql"
      environment-name: npm
      node-version: "20"
      emscripten-version: "3.1.64"
      ubuntu-version: "22.04"
      generate: true